version: "3.4"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1433:1433
    volumes:
      - /var/opt/mssql
      - ./:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c 'chmod +x ./init-database.sh; ./init-database.sh & /opt/mssql/bin/sqlservr;'
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: "S3cur3P@ssW0rd!"
      DATABASE_NAME: bdpayroll
      
  api:
    build:
      context: .
      dockerfile: Api/Dockerfile
    depends_on:
      - sqlserver