version: "3.4"

services:
  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - "1433:1433"
    entrypoint: /bin/bash   
    expose:
      - 1433
    command: sh -c 'chmod +x ./init-database.sh; ./init-database.sh & /opt/mssql/bin/sqlserver;'
    environment:
      SA_PASSWORD: "S3cur3P@ssW0rd!"
      ACCEPT_EULA: "Y"
      DATABASE_NAME: bdpayroll
  api:
    build:
      context: .
      dockerfile: Api/Dockerfile
    depends_on:
      - db